### ISSUE TITLE
NVR Muxer

### ISSUE THREAD

**Issue by dbl0null** [deepch/RTSPtoHLS#1]
Привет! 
Пользуясь случаем низкий тебе поклон за проекты и особенно за vdk!
[Тут](https://github.com/deepch/RTSPtoHLS/blob/main/stream.go#L9) имортится отсутствуюйщий в vdk модуль github.com/deepch/vdk/format/nvr

Не мог бы ты пожалуйста добавить его в vdk?
Понимаю, что он не имеет прямого отношения к именно "toHLS", но было бы очень круто)
Да и этот проект без него не соберется

Еще раз спасибо огромное за работу, с интересом слежу!

**Comment by deepch** [comment]
Приветствую, этот модуль ещё не закончен возможно позднее  я его и добавлю но пока что он не готов.
